name: Build and publish
on:
    release:
        types: [published, edited]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
              with:
                  ref: ${{ github.event.release.tag_name }}

            - name: Setup Node
              uses: actions/setup-node@v3

            - uses: JasonEtco/build-and-tag-action@v2
              env:
                  GITHUB_TOKEN: ${{ github.token }}
