name: Build and test
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  ref: ${{ github.event.release.tag_name }}

            - name: Setup Node
              uses: actions/setup-node@v6

            - name: Install deps
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build

            - name: Test
              run: npm run test
