name: Build and test
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
              with:
                  ref: ${{ github.event.release.tag_name }}

            - name: Setup Node
              uses: actions/setup-node@v3

            - name: Install deps
              run: npm ci
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test
